### ISSUE TITLE
ExBuffer 环形队列读写起始位置

### ISSUE THREAD

**Issue by xurendong** [xiaoping6688/node-socket#1]
如果缓存长度30字节，位置为 0 到 29，已有未读数据10字节位于 10 到 19，则 _readOffset = 10，_putOffset = 20，此时新增数据20字节，队列尾部存10字节，队列头部存10字节，此时 _putOffset = 10，将与 _readOffset 重合？

只要 新增数据长度 + 有效数据长度 = 缓存长度，且缓存尾容量不足以放下整个新增数据，需要部分或全部放到缓存头，就会导致重合？

建议将：
        //当前缓冲区已经不能满足次数数据了
        if (len + getLen() > _buffer.length) {
            var ex = Math.ceil((len + getLen()) / 1024); //每次扩展1kb
            var tmp = Buffer.alloc(ex * 1024);

修改为：
        //当前缓冲区已经不能满足次数数据了
        if (len + getLen() >= _buffer.length) {
            var ex = Math.ceil((len + getLen()) / 1024); //每次扩展1kb
            var tmp = Buffer.alloc(ex * 1024 + 1);
1、相等时就扩充缓存
2、多一字节以避免 (len + getLen()) / 1024 刚好为整数使得新旧缓存大小一样

需要考虑 1024 + 1 字节可能导致 内存 或 CPU Cache 未对齐？
要不就直接 Buffer.alloc(ex * 1024 + 1024); 算了。

另外，直接迁移有用数据到新缓存，而不是先拷贝整个老缓存到新缓存再整理，是否能提高效率？

**Comment by xiaoping6688** [comment]
👍
